# Generated by Django 2.1.5 on 2019-02-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='message_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
